### PR TITLE
Workflow Badges

### PR DESCRIPTION
**Pull request by ClemensLinnhoff**
**Reference to a related issue in the repository**
#50 

**Add a description**
Since all Credibility Assessment Levels are now integrated into one workflow, only one badge can be displayed in the readme.

**Take this checklist as orientation for yourself, if this PR is ready for Maintainer Review**
- [x] My suggestion follows the [governance rules](https://github.com/openMSL/governance-and-documentation).
- [x] All commits of this PR are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- [x] My changes generate no errors when passing CI tests. 
- [x] I updated all documentation (readmes incl. figures) according to my changes.
- [x] I have successfully implemented and tested my fix/feature locally.
- [x] Appropriate reviewer(s) are assigned.

### CODE REVIEW

**Comment by ClemensLinnhoff** [comment]
Is the rather generic term "Test Pipeline" okay for the workflow/badge? An alternative would be to name it "Credibility Assessment".

Which level is passed has to be determined by looking into the pipeline. Or should we put the highest achieved credibility level next to the badge?

**Comment by jdsika** [comment]
I am in favor of showing a single batch and rate a well structured workflow file over multiple batches

**Comment by jdsika** [comment]
"Credibility assessment" sounds good also in combination with the level! 
Can we make a warning+hint if it partly failed?

**Comment by ClemensLinnhoff** [comment]
> "Credibility assessment" sounds good also in combination with the level! Can we make a warning+hint if it partly failed?

If it partly fails, it will show the badge as failed. You can then go into the action and see which parts failed. However, since you can only merge into main, when the pipeline passes, this is a rather theoretical issue. The badge will probably never show "failed" in the main readme, as it is not possible to merge into main with a failing workflow.

**Review by LukasElster — APPROVED** [review]

**Pull request merged**
